# coding: utf-8

# flake8: noqa

"""
    Shorty API

    A modern URL shortener with team collaboration, SSO, and SCIM support.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# Define package exports
__all__ = [
    "ApiKeysApi",
    "AuthApi",
    "GroupsApi",
    "LinksApi",
    "OrganizationsApi",
    "TagsApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "ApikeysAPIKeyResponse",
    "ApikeysCreateAPIKeyRequest",
    "ApikeysCreateAPIKeyResponse",
    "AuthAuthResponse",
    "AuthChangePasswordRequest",
    "AuthLoginRequest",
    "AuthRegisterRequest",
    "AuthUserResponse",
    "GroupsAddMemberRequest",
    "GroupsCreateGroupRequest",
    "GroupsGroupResponse",
    "GroupsMemberResponse",
    "GroupsUpdateGroupRequest",
    "GroupsUpdateMemberRequest",
    "LinksCreateLinkRequest",
    "LinksLinkResponse",
    "LinksUpdateLinkRequest",
    "OrganizationsAddMemberRequest",
    "OrganizationsCreateOrgRequest",
    "OrganizationsMemberResponse",
    "OrganizationsOrgResponse",
    "OrganizationsUpdateMemberRequest",
    "OrganizationsUpdateOrgRequest",
    "TagsSetTagsRequest",
    "TagsTagResponse",
]

# import apis into sdk package
from shorty_client.api.api_keys_api import ApiKeysApi as ApiKeysApi
from shorty_client.api.auth_api import AuthApi as AuthApi
from shorty_client.api.groups_api import GroupsApi as GroupsApi
from shorty_client.api.links_api import LinksApi as LinksApi
from shorty_client.api.organizations_api import OrganizationsApi as OrganizationsApi
from shorty_client.api.tags_api import TagsApi as TagsApi

# import ApiClient
from shorty_client.api_response import ApiResponse as ApiResponse
from shorty_client.api_client import ApiClient as ApiClient
from shorty_client.configuration import Configuration as Configuration
from shorty_client.exceptions import OpenApiException as OpenApiException
from shorty_client.exceptions import ApiTypeError as ApiTypeError
from shorty_client.exceptions import ApiValueError as ApiValueError
from shorty_client.exceptions import ApiKeyError as ApiKeyError
from shorty_client.exceptions import ApiAttributeError as ApiAttributeError
from shorty_client.exceptions import ApiException as ApiException

# import models into sdk package
from shorty_client.models.apikeys_api_key_response import ApikeysAPIKeyResponse as ApikeysAPIKeyResponse
from shorty_client.models.apikeys_create_api_key_request import ApikeysCreateAPIKeyRequest as ApikeysCreateAPIKeyRequest
from shorty_client.models.apikeys_create_api_key_response import ApikeysCreateAPIKeyResponse as ApikeysCreateAPIKeyResponse
from shorty_client.models.auth_auth_response import AuthAuthResponse as AuthAuthResponse
from shorty_client.models.auth_change_password_request import AuthChangePasswordRequest as AuthChangePasswordRequest
from shorty_client.models.auth_login_request import AuthLoginRequest as AuthLoginRequest
from shorty_client.models.auth_register_request import AuthRegisterRequest as AuthRegisterRequest
from shorty_client.models.auth_user_response import AuthUserResponse as AuthUserResponse
from shorty_client.models.groups_add_member_request import GroupsAddMemberRequest as GroupsAddMemberRequest
from shorty_client.models.groups_create_group_request import GroupsCreateGroupRequest as GroupsCreateGroupRequest
from shorty_client.models.groups_group_response import GroupsGroupResponse as GroupsGroupResponse
from shorty_client.models.groups_member_response import GroupsMemberResponse as GroupsMemberResponse
from shorty_client.models.groups_update_group_request import GroupsUpdateGroupRequest as GroupsUpdateGroupRequest
from shorty_client.models.groups_update_member_request import GroupsUpdateMemberRequest as GroupsUpdateMemberRequest
from shorty_client.models.links_create_link_request import LinksCreateLinkRequest as LinksCreateLinkRequest
from shorty_client.models.links_link_response import LinksLinkResponse as LinksLinkResponse
from shorty_client.models.links_update_link_request import LinksUpdateLinkRequest as LinksUpdateLinkRequest
from shorty_client.models.organizations_add_member_request import OrganizationsAddMemberRequest as OrganizationsAddMemberRequest
from shorty_client.models.organizations_create_org_request import OrganizationsCreateOrgRequest as OrganizationsCreateOrgRequest
from shorty_client.models.organizations_member_response import OrganizationsMemberResponse as OrganizationsMemberResponse
from shorty_client.models.organizations_org_response import OrganizationsOrgResponse as OrganizationsOrgResponse
from shorty_client.models.organizations_update_member_request import OrganizationsUpdateMemberRequest as OrganizationsUpdateMemberRequest
from shorty_client.models.organizations_update_org_request import OrganizationsUpdateOrgRequest as OrganizationsUpdateOrgRequest
from shorty_client.models.tags_set_tags_request import TagsSetTagsRequest as TagsSetTagsRequest
from shorty_client.models.tags_tag_response import TagsTagResponse as TagsTagResponse

