# coding: utf-8

"""
    Shorty API

    A modern URL shortener with team collaboration, SSO, and SCIM support.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from shorty_client.api.tags_api import TagsApi


class TestTagsApi(unittest.TestCase):
    """TagsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TagsApi()

    def tearDown(self) -> None:
        pass

    def test_groups_id_tags_get(self) -> None:
        """Test case for groups_id_tags_get

        List tags in a group
        """
        pass

    def test_links_slug_tags_get(self) -> None:
        """Test case for links_slug_tags_get

        Get link tags
        """
        pass

    def test_links_slug_tags_put(self) -> None:
        """Test case for links_slug_tags_put

        Set link tags
        """
        pass

    def test_links_slug_tags_tag_delete(self) -> None:
        """Test case for links_slug_tags_tag_delete

        Remove tag from link
        """
        pass

    def test_links_slug_tags_tag_post(self) -> None:
        """Test case for links_slug_tags_tag_post

        Add tag to link
        """
        pass

    def test_tags_get(self) -> None:
        """Test case for tags_get

        List tags
        """
        pass


if __name__ == '__main__':
    unittest.main()
