# coding: utf-8

"""
    Shorty API

    A modern URL shortener with team collaboration, SSO, and SCIM support.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from shorty_client.api.auth_api import AuthApi


class TestAuthApi(unittest.TestCase):
    """AuthApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AuthApi()

    def tearDown(self) -> None:
        pass

    def test_auth_login_post(self) -> None:
        """Test case for auth_login_post

        Login
        """
        pass

    def test_auth_logout_post(self) -> None:
        """Test case for auth_logout_post

        Logout
        """
        pass

    def test_auth_me_get(self) -> None:
        """Test case for auth_me_get

        Get current user
        """
        pass

    def test_auth_password_put(self) -> None:
        """Test case for auth_password_put

        Change password
        """
        pass

    def test_auth_register_post(self) -> None:
        """Test case for auth_register_post

        Register a new user
        """
        pass


if __name__ == '__main__':
    unittest.main()
