# coding: utf-8

"""
    Shorty API

    A modern URL shortener with team collaboration, SSO, and SCIM support.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from shorty_client.models.groups_add_member_request import GroupsAddMemberRequest

class TestGroupsAddMemberRequest(unittest.TestCase):
    """GroupsAddMemberRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GroupsAddMemberRequest:
        """Test GroupsAddMemberRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GroupsAddMemberRequest`
        """
        model = GroupsAddMemberRequest()
        if include_optional:
            return GroupsAddMemberRequest(
                email = '',
                role = 'admin'
            )
        else:
            return GroupsAddMemberRequest(
                email = '',
                role = 'admin',
        )
        """

    def testGroupsAddMemberRequest(self):
        """Test GroupsAddMemberRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
