# coding: utf-8

"""
    Shorty API

    A modern URL shortener with team collaboration, SSO, and SCIM support.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from shorty_client.api.links_api import LinksApi


class TestLinksApi(unittest.TestCase):
    """LinksApi unit test stubs"""

    def setUp(self) -> None:
        self.api = LinksApi()

    def tearDown(self) -> None:
        pass

    def test_groups_id_links_get(self) -> None:
        """Test case for groups_id_links_get

        List links in a group
        """
        pass

    def test_groups_id_links_post(self) -> None:
        """Test case for groups_id_links_post

        Create a link
        """
        pass

    def test_links_get(self) -> None:
        """Test case for links_get

        Search links
        """
        pass

    def test_links_slug_delete(self) -> None:
        """Test case for links_slug_delete

        Delete a link
        """
        pass

    def test_links_slug_get(self) -> None:
        """Test case for links_slug_get

        Get a link by slug
        """
        pass

    def test_links_slug_put(self) -> None:
        """Test case for links_slug_put

        Update a link
        """
        pass


if __name__ == '__main__':
    unittest.main()
