# coding: utf-8

"""
    Shorty API

    A modern URL shortener with team collaboration, SSO, and SCIM support.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from shorty_client.api.api_keys_api import ApiKeysApi


class TestApiKeysApi(unittest.TestCase):
    """ApiKeysApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ApiKeysApi()

    def tearDown(self) -> None:
        pass

    def test_api_keys_get(self) -> None:
        """Test case for api_keys_get

        List API keys
        """
        pass

    def test_api_keys_id_delete(self) -> None:
        """Test case for api_keys_id_delete

        Delete an API key
        """
        pass

    def test_api_keys_post(self) -> None:
        """Test case for api_keys_post

        Create an API key
        """
        pass


if __name__ == '__main__':
    unittest.main()
