# coding: utf-8

"""
    Shorty API

    A modern URL shortener with team collaboration, SSO, and SCIM support.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from shorty_client.models.auth_user_response import AuthUserResponse

class TestAuthUserResponse(unittest.TestCase):
    """AuthUserResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AuthUserResponse:
        """Test AuthUserResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AuthUserResponse`
        """
        model = AuthUserResponse()
        if include_optional:
            return AuthUserResponse(
                email = '',
                has_password = True,
                id = '',
                name = '',
                system_role = ''
            )
        else:
            return AuthUserResponse(
        )
        """

    def testAuthUserResponse(self):
        """Test AuthUserResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
