# coding: utf-8

"""
    Shorty API

    A modern URL shortener with team collaboration, SSO, and SCIM support.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from shorty_client.api.groups_api import GroupsApi


class TestGroupsApi(unittest.TestCase):
    """GroupsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = GroupsApi()

    def tearDown(self) -> None:
        pass

    def test_groups_get(self) -> None:
        """Test case for groups_get

        List groups
        """
        pass

    def test_groups_id_delete(self) -> None:
        """Test case for groups_id_delete

        Delete a group
        """
        pass

    def test_groups_id_get(self) -> None:
        """Test case for groups_id_get

        Get a group
        """
        pass

    def test_groups_id_members_get(self) -> None:
        """Test case for groups_id_members_get

        List group members
        """
        pass

    def test_groups_id_members_post(self) -> None:
        """Test case for groups_id_members_post

        Add group member
        """
        pass

    def test_groups_id_members_user_id_delete(self) -> None:
        """Test case for groups_id_members_user_id_delete

        Remove group member
        """
        pass

    def test_groups_id_members_user_id_put(self) -> None:
        """Test case for groups_id_members_user_id_put

        Update group member
        """
        pass

    def test_groups_id_put(self) -> None:
        """Test case for groups_id_put

        Update a group
        """
        pass

    def test_groups_post(self) -> None:
        """Test case for groups_post

        Create a group
        """
        pass


if __name__ == '__main__':
    unittest.main()
