# coding: utf-8

"""
    Shorty API

    A modern URL shortener with team collaboration, SSO, and SCIM support.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from shorty_client.models.links_link_response import LinksLinkResponse

class TestLinksLinkResponse(unittest.TestCase):
    """LinksLinkResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LinksLinkResponse:
        """Test LinksLinkResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LinksLinkResponse`
        """
        model = LinksLinkResponse()
        if include_optional:
            return LinksLinkResponse(
                click_count = 56,
                created_at = '',
                description = '',
                group_id = '',
                id = '',
                is_public = True,
                is_unread = True,
                slug = '',
                title = '',
                updated_at = '',
                url = ''
            )
        else:
            return LinksLinkResponse(
        )
        """

    def testLinksLinkResponse(self):
        """Test LinksLinkResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
