# coding: utf-8

"""
    Shorty API

    A modern URL shortener with team collaboration, SSO, and SCIM support.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from shorty_client.models.auth_change_password_request import AuthChangePasswordRequest

class TestAuthChangePasswordRequest(unittest.TestCase):
    """AuthChangePasswordRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AuthChangePasswordRequest:
        """Test AuthChangePasswordRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AuthChangePasswordRequest`
        """
        model = AuthChangePasswordRequest()
        if include_optional:
            return AuthChangePasswordRequest(
                current_password = '',
                new_password = '01234567'
            )
        else:
            return AuthChangePasswordRequest(
                current_password = '',
                new_password = '01234567',
        )
        """

    def testAuthChangePasswordRequest(self):
        """Test AuthChangePasswordRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
