# coding: utf-8

"""
    Shorty API

    A modern URL shortener with team collaboration, SSO, and SCIM support.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from shorty_client.api.organizations_api import OrganizationsApi


class TestOrganizationsApi(unittest.TestCase):
    """OrganizationsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = OrganizationsApi()

    def tearDown(self) -> None:
        pass

    def test_organizations_get(self) -> None:
        """Test case for organizations_get

        List organizations
        """
        pass

    def test_organizations_id_delete(self) -> None:
        """Test case for organizations_id_delete

        Delete an organization
        """
        pass

    def test_organizations_id_get(self) -> None:
        """Test case for organizations_id_get

        Get an organization
        """
        pass

    def test_organizations_id_members_get(self) -> None:
        """Test case for organizations_id_members_get

        List organization members
        """
        pass

    def test_organizations_id_members_post(self) -> None:
        """Test case for organizations_id_members_post

        Add organization member
        """
        pass

    def test_organizations_id_members_user_id_delete(self) -> None:
        """Test case for organizations_id_members_user_id_delete

        Remove organization member
        """
        pass

    def test_organizations_id_members_user_id_put(self) -> None:
        """Test case for organizations_id_members_user_id_put

        Update organization member
        """
        pass

    def test_organizations_id_put(self) -> None:
        """Test case for organizations_id_put

        Update an organization
        """
        pass

    def test_organizations_post(self) -> None:
        """Test case for organizations_post

        Create an organization
        """
        pass


if __name__ == '__main__':
    unittest.main()
