# coding: utf-8

"""
    Shorty API

    A modern URL shortener with team collaboration, SSO, and SCIM support.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from shorty_client.models.groups_create_group_request import GroupsCreateGroupRequest

class TestGroupsCreateGroupRequest(unittest.TestCase):
    """GroupsCreateGroupRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GroupsCreateGroupRequest:
        """Test GroupsCreateGroupRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GroupsCreateGroupRequest`
        """
        model = GroupsCreateGroupRequest()
        if include_optional:
            return GroupsCreateGroupRequest(
                description = '',
                name = '',
                organization_id = ''
            )
        else:
            return GroupsCreateGroupRequest(
                name = '',
        )
        """

    def testGroupsCreateGroupRequest(self):
        """Test GroupsCreateGroupRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
