# coding: utf-8

# flake8: noqa
"""
    Shorty API

    A modern URL shortener with team collaboration, SSO, and SCIM support.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

# import models into model package
from shorty_client.models.apikeys_api_key_response import ApikeysAPIKeyResponse
from shorty_client.models.apikeys_create_api_key_request import ApikeysCreateAPIKeyRequest
from shorty_client.models.apikeys_create_api_key_response import ApikeysCreateAPIKeyResponse
from shorty_client.models.auth_auth_response import AuthAuthResponse
from shorty_client.models.auth_change_password_request import AuthChangePasswordRequest
from shorty_client.models.auth_login_request import AuthLoginRequest
from shorty_client.models.auth_register_request import AuthRegisterRequest
from shorty_client.models.auth_user_response import AuthUserResponse
from shorty_client.models.groups_add_member_request import GroupsAddMemberRequest
from shorty_client.models.groups_create_group_request import GroupsCreateGroupRequest
from shorty_client.models.groups_group_response import GroupsGroupResponse
from shorty_client.models.groups_member_response import GroupsMemberResponse
from shorty_client.models.groups_update_group_request import GroupsUpdateGroupRequest
from shorty_client.models.groups_update_member_request import GroupsUpdateMemberRequest
from shorty_client.models.links_create_link_request import LinksCreateLinkRequest
from shorty_client.models.links_link_response import LinksLinkResponse
from shorty_client.models.links_update_link_request import LinksUpdateLinkRequest
from shorty_client.models.organizations_add_member_request import OrganizationsAddMemberRequest
from shorty_client.models.organizations_create_org_request import OrganizationsCreateOrgRequest
from shorty_client.models.organizations_member_response import OrganizationsMemberResponse
from shorty_client.models.organizations_org_response import OrganizationsOrgResponse
from shorty_client.models.organizations_update_member_request import OrganizationsUpdateMemberRequest
from shorty_client.models.organizations_update_org_request import OrganizationsUpdateOrgRequest
from shorty_client.models.tags_set_tags_request import TagsSetTagsRequest
from shorty_client.models.tags_tag_response import TagsTagResponse

